CREATE TABLE items (
    id           INT PRIMARY KEY,
    name         VARCHAR(50) UNIQUE NOT NULL,
    ko_name      VARCHAR(50),   
    category     VARCHAR(50),
    fling_power  INT,          
    description  TEXT,
    effect       TEXT
);

INSERT INTO items
    (id, name, ko_name, category, fling_power, description, effect)
VALUES
    (1697, 'ability-shield', NULL, 'held-items', NULL, NULL, NULL),
    (713, 'abomasite', '눈설왕나이트', 'mega-stones', 80, '눈설왕에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Abomasnow to Mega Evolve into Mega Abomasnow.'),
    (716, 'absolite', '앱솔나이트', 'mega-stones', 80, '앱솔에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Absol to Mega Evolve into Mega Absol.'),
    (2265, 'absolite-z', NULL, 'mega-stones', 80, NULL, NULL),
    (588, 'absorb-bulb', '구근', 'held-items', 30, '단 한 번 쓰면 없어지는 구근. 지니게 하고 물 기술을 받으면 특수공격이 올라간다.', 'Held: Raises the holder’s Special Attack by one stage when it takes Water-type damage.'),
    (112, 'adamant-orb', '금강옥', 'species-specific', 60, '디아루가에게 지니게 하면 드래곤과 강철타입 기술의 위력이 올라가는 반짝반짝 빛나는 구슬.', 'Boosts the damage from Dialga’s Dragon-type and Steel-type moves by 20%.'),
    (883, 'adrenaline-orb', '주눅구슬', 'held-items', 30, '포켓몬에게 지니게 하면 위협을 받았을 때 스피드가 올라간다.', 'Makes wild Pokémon more likely to summon allies.  Held: increases the holder’s Speed by one stage when affected by Intimidate.'),
    (711, 'aerodactylite', '프테라나이트', 'mega-stones', 80, '프테라에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Aerodactyl to Mega Evolve into Mega Aerodactyl.'),
    (706, 'aggronite', '보스로라나이트', 'mega-stones', 80, '보스로라에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Aggron to Mega Evolve into Mega Aggron.'),
    (139, 'aguav-berry', '아바열매', 'picky-healing', 10, '포켓몬에게 지니게 하면 위급할 때 HP를 회복한다. 싫어하는 맛이면 혼란에 빠진다.', 'Held: Consumed at 1/2 max HP to restore 1/8 max HP. Confuses Pokémon that dislike bitter flavor.'),
    (584, 'air-balloon', '풍선', 'held-items', 10, '포켓몬에게 지니게 하면 포켓몬이 허공에 뜬다. 공격을 받으면 터져버린다.', 'Held: Grants immunity to Ground-type moves, Spikes, and Toxic Spikes. Consumed when the holder takes damage from a move.'),
    (718, 'alakazite', '후디나이트', 'mega-stones', 80, '후딘에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Alakazam to Mega Evolve into Mega Alakazam.'),
    (796, 'altarianite', '파비코리나이트', 'mega-stones', 80, '파비코리에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Altaria to Mega Evolve into Mega Altaria.'),
    (697, 'ampharosite', '전룡나이트', 'mega-stones', 80, '전룡에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Ampharos to Mega Evolve into Mega Ampharos.'),
    (182, 'apicot-berry', '규살열매', 'in-a-pinch', 10, '포켓몬에게 지니게 하면 위급할 때 자신의 특수방어가 올라간다.', 'Held: Consumed at 1/4 max HP to boost Special Defense.'),
    (683, 'assault-vest', '돌격조끼', 'held-items', 80, '공격적으로 변하는 조끼. 지니게 하면 특수방어가 올라가지만 변화 기술을 쓸 수 없게 된다.', 'Raises the holder’s Special Defense to 1.5×.  Prevents the holder from selecting a status move.'),
    (798, 'audinite', '다부니나이트', 'mega-stones', 80, '다부니에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Audino to Mega Evolve into Mega Audino.'),
    (176, 'babiri-berry', '바리비열매', 'type-protection', 10, '포켓몬에게 지니게 하면 효과가 뛰어난 강철 기술을 당했을 때 위력이 약해진다.', 'Held: Consumed when struck by a super-effective Steel-type attack to halve the damage.'),
    (707, 'banettite', '다크펫나이트', 'mega-stones', 80, '다크펫에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Banette to Mega Evolve into Mega Banette.'),
    (2255, 'barbaracite', NULL, 'mega-stones', 80, NULL, NULL),
    (2275, 'baxcalibrite', NULL, 'mega-stones', 80, NULL, NULL),
    (811, 'beedrillite', '독침붕나이트', 'mega-stones', 80, '독침붕에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Beedrill to Mega Evolve into Mega Beedrill.'),
    (273, 'big-root', '큰뿌리', 'held-items', 10, '지니게 하면 HP 흡수 기술을 썼을 때 여느 때보다 많은 HP를 자신이 회복할 수 있다.', 'Held: Increases HP recovered from draining moves, Ingrain, and Aqua Ring by 3/10 (30%).'),
    (587, 'binding-band', '조임밴드', 'held-items', 30, '조이기 기술을 보조하는 밴드. 지니게 하면 조이기 기술의 위력이 강해진다.', 'Held: Doubles the per-turn damage of multi-turn trapping moves.'),
    (218, 'black-belt', '검은띠', 'type-enhancement', 30, '마음을 긴장시키는 띠. 지니게 하면 격투타입 기술의 위력이 올라간다.', 'Held: Fighting-Type moves from holder do 20% more damage.'),
    (217, 'black-glasses', '검은안경', 'type-enhancement', 30, '괴상하게 보이는 안경. 지니게 하면 악타입 기술의 위력이 올라간다.', 'Held: Dark-Type moves from holder do 20% more damage.'),
    (258, 'black-sludge', '검은오물', 'held-items', 30, '지니게 하면 독타입의 포켓몬은 조금씩 HP를 회복한다. 그 이외의 타입은 HP가 줄어 버린다.', 'Held: Poison-type holder recovers 1/16 (6.25%) max HP each turn. Non-Poison-Types take 1/8 (12.5%) max HP damage.'),
    (1662, 'blank-plate', NULL, 'plates', NULL, NULL, NULL),
    (700, 'blastoisinite', '거북왕나이트', 'mega-stones', 80, '거북왕에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Blastoise to Mega Evolve into Mega Blastoise.'),
    (703, 'blazikenite', '번치코나이트', 'mega-stones', 80, '번치코에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Blaziken to Mega Evolve into Mega Blaziken.'),
    (1179, 'blunder-policy', '허탕보험', 'held-items', 80, '명중률에 의해 기술이 빗나갔을 때 스피드가 크게 올라간다.', NULL),
    (1696, 'booster-energy', NULL, 'held-items', NULL, NULL, NULL),
    (190, 'bright-powder', '반짝가루', 'held-items', 10, '반짝반짝 빛나는 가루. 지니게 하면 빛이 상대를 혼란시켜 기술이 명중되기 어려워진다.', 'Held: Increases the holder’s evasion by 1/9 (11 1/9%).'),
    (565, 'burn-drive', '블레이즈카세트', 'species-specific', 70, '게노세크트에게 지니게 하면 테크노버스터라는 기술이 불꽃타입으로 바뀌는 카세트.', 'Grants Genesect a red, Fire-type Techno Blast.'),
    (808, 'cameruptite', '폭타나이트', 'mega-stones', 80, '폭타에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Camerupt to Mega Evolve into Mega Camerupt.'),
    (589, 'cell-battery', '충전지', 'held-items', 30, '단 한 번 쓰면 없어지는 충전지. 지니게 하고 전기 기술을 받으면 공격이 올라간다.', 'Held: Raises the holder’s Attack by one stage when it takes Electric-type damage.'),
    (2248, 'chandelurite', NULL, 'mega-stones', 80, NULL, NULL),
    (226, 'charcoal', '목탄', 'type-enhancement', 30, '물건을 태우는 연료. 지니게 하면 불꽃타입 기술의 위력이 올라간다.', 'Held: Fire-Type moves from holder do 20% more damage.'),
    (699, 'charizardite-x', '리자몽나이트X', 'mega-stones', 80, '리자몽에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Charizard to Mega Evolve into Mega Charizard X.'),
    (717, 'charizardite-y', '리자몽나이트Y', 'mega-stones', 80, '리자몽에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Charizard to Mega Evolve into Mega Charizard Y.'),
    (172, 'charti-berry', '루미열매', 'type-protection', 10, '포켓몬에게 지니게 하면 효과가 뛰어난 바위 기술을 당했을 때 위력이 약해진다.', 'Held: Consumed when struck by a super-effective Rock-type attack to halve the damage.'),
    (2249, 'chesnaughtite', NULL, 'mega-stones', 80, NULL, NULL),
    (177, 'chilan-berry', '카리열매', 'type-protection', 10, '포켓몬에게 지니게 하면 노말 기술을 당했을 때 위력이 약해진다.', 'Held: Consumed when struck by a Normal-type attack to halve the damage.'),
    (566, 'chill-drive', '프리즈카세트', 'species-specific', 70, '게노세크트에게 지니게 하면 테크노버스터라는 기술이 얼음타입으로 바뀌는 카세트.', 'Grants Genesect a white, Ice-type Techno Blast.'),
    (2264, 'chimechite', NULL, 'mega-stones', 80, NULL, NULL),
    (197, 'choice-band', '구애머리띠', 'choice', 10, '기술을 구애받는 머리띠. 지니게 하면 공격은 올라가지만 똑같은 기술밖에 쓰지 못한다.', 'Held: Increases Attack by 50%, but restricts the holder to only one move.'),
    (264, 'choice-scarf', '구애스카프', 'choice', 10, '기술을 구애받는 스카프. 지니게 하면 스피드는 올라가지만 같은 기술밖에 쓸 수 없다.', 'Held: Increases Speed by 50%, but restricts the holder to only one move.'),
    (274, 'choice-specs', '구애안경', 'choice', 10, '기술을 구애받는 안경. 지니게 하면 특수공격이 올라가지만 같은 기술밖에 쓸 수 없다.', 'Held: Increases Special Attack by 50%, but restricts the holder to only one move.'),
    (166, 'chople-berry', '로플열매', 'type-protection', 10, '포켓몬에게 지니게 하면 효과가 뛰어난 격투 기술을 당했을 때 위력이 약해진다.', 'Held: Consumed when struck by a super-effective Fighting-type attack to halve the damage.'),
    (1698, 'clear-amulet', NULL, 'held-items', NULL, NULL, NULL),
    (2233, 'clefablite', NULL, 'mega-stones', 80, NULL, NULL),
    (169, 'coba-berry', '바코열매', 'type-protection', 10, '포켓몬에게 지니게 하면 효과가 뛰어난 비행 기술을 당했을 때 위력이 약해진다.', 'Held: Consumed when struck by a super-effective Flying-type attack to halve the damage.'),
    (175, 'colbur-berry', '마코열매', 'type-protection', 10, '포켓몬에게 지니게 하면 효과가 뛰어난 악 기술을 당했을 때 위력이 약해진다.', 'Held: Consumed when struck by a super-effective Dark-type attack to halve the damage.'),
    (2108, 'cornerstone-mask', NULL, 'held-items', NULL, NULL, NULL),
    (1701, 'covert-cloak', NULL, 'held-items', NULL, NULL, NULL),
    (2271, 'crabominite', NULL, 'mega-stones', 80, NULL, NULL),
    (187, 'custap-berry', '애슈열매', 'in-a-pinch', 10, '포켓몬에게 지니게 하면 위급할 때 한 번만 행동이 빨라진다.', 'Held: Consumed at 1/4 max HP when using a move to go first.'),
    (262, 'damp-rock', '축축한바위', 'held-items', 60, '지니게 한 포켓몬이 비바라기를 쓰면 여느 때보다 비 내리는 시간이 길어진다.', 'Held: Rain Dance by the holder lasts 8 rounds instead of 5.'),
    (2242, 'darkranite', NULL, 'mega-stones', 80, NULL, NULL),
    (204, 'deep-sea-scale', '심해의비늘', 'species-specific', 30, '진주몽에게 지니게 하면 특수방어가 올라가는 비늘. 연한 분홍색으로 빛난다.', 'Doubles Clamperl’s Special Defense. Traded on a Clamperl: Holder evolves into Gorebyss.'),
    (203, 'deep-sea-tooth', '심해의이빨', 'species-specific', 90, '진주몽에게 지니게 하면 특수공격이 올라가는 이빨. 날카로운 은색으로 빛난다.', 'Doubles Clamperl’s Special Attack. Traded on a Clamperl: Holder evolves into Huntail.'),
    (2250, 'delphoxite', NULL, 'mega-stones', 80, NULL, NULL),
    (257, 'destiny-knot', '빨간실', 'held-items', 10, '가늘고 긴 새빨간 실. 지니게 하면 자신이 헤롱헤롱해졌을 때 상대도 헤롱헤롱해지게 된다.', 'Held: Infatuates opposing Pokémon when holder is inflicted with infatuation.'),
    (805, 'diancite', '디안시나이트', 'mega-stones', 80, '디안시에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Diancie to Mega Evolve into Mega Diancie.'),
    (56, 'dire-hit', '크리티컬커터', 'stat-boosts', 30, '급소 명중률이 크게 올라간다. 한 번밖에 쓸 수 없다. 포켓몬을 볼에 넣어버리면 원래대로 되돌아간다.', 'Increases the chance of a critical hit in battle.  Raises happiness.'),
    (563, 'douse-drive', '아쿠아카세트', 'species-specific', 70, '게노세크트에게 지니게 하면 테크노버스터라는 기술이 물타입으로 바뀌는 카세트.', 'Grants Genesect a blue, Water-type Techno Blast.'),
    (288, 'draco-plate', '용의플레이트', 'plates', 90, '드래곤타입의 석판. 지니게 하면 드래곤타입 기술의 위력이 강해진다.', 'Held: Dragon-Type moves from holder do 20% more damage. Changes Arceus’s and Judgment’s type to Dragon.'),
    (2256, 'dragalgite', NULL, 'mega-stones', 80, NULL, NULL),
    (227, 'dragon-fang', '용의이빨', 'type-enhancement', 70, '단단하고 날카로운 이빨. 지니게 하면 드래곤타입 기술의 위력이 올라간다.', 'Held: Dragon-Type moves from holder do 20% more damage.'),
    (2236, 'dragoninite', NULL, 'mega-stones', 80, NULL, NULL),
    (2259, 'drampanite', NULL, 'mega-stones', 80, NULL, NULL),
    (289, 'dread-plate', '공포플레이트', 'plates', 90, '악타입의 석판. 지니게 하면 악타입 기술의 위력이 강해진다.', 'Held: Dark-Type moves from holder do 20% more damage. Changes Arceus’s and Judgment’s type to Dark.'),
    (282, 'earth-plate', '대지플레이트', 'plates', 90, '땅타입의 석판. 지니게 하면 땅타입 기술의 위력이 강해진다.', 'Held: Ground-Type moves from holder do 20% more damage. Changes Arceus’s and Judgment’s type to Ground.'),
    (2247, 'eelektrossite', NULL, 'mega-stones', 80, NULL, NULL),
    (590, 'eject-button', '탈출버튼', 'held-items', 30, '지니게 하고 기술을 받으면 배틀에서 탈출하여 지닌 포켓몬과 교체할 수 있다.', 'Held: When the holder takes damage from a move, it switches out for a party Pokémon of the Trainer’s choice.'),
    (1177, 'eject-pack', '탈출팩', 'held-items', 50, '지니게 한 포켓몬의 능력이 떨어지면 지닌 포켓몬과 교체한다.', NULL),
    (898, 'electric-seed', '일렉트릭시드', 'held-items', 10, '포켓몬에게 지니게 하면 일렉트릭필드일 때 사용하여 방어가 올라간다.', 'Held: Consumed on Electric Terrain and raises the holder’s Defense by one stage.'),
    (2243, 'emboarite', NULL, 'mega-stones', 80, NULL, NULL),
    (581, 'eviolite', '진화의휘석', 'held-items', 40, '진화의 이상한 덩어리. 지니게 하면 진화 전 포켓몬의 방어와 특수방어가 올라간다.', 'Held: Holder has 1.5× Defense and Special Defense, as long as it’s not fully evolved.'),
    (2244, 'excadrite', NULL, 'mega-stones', 80, NULL, NULL),
    (245, 'expert-belt', '달인의띠', 'held-items', 10, '오래 사용한 까만 띠. 지니게 하면 효과가 뛰어날 때 기술의 위력이 조금 올라간다.', 'Held: Holder’s Super Effective moves do 20% extra damage.'),
    (2105, 'fairy-feather', NULL, 'held-items', NULL, NULL, NULL),
    (2261, 'falinksite', NULL, 'mega-stones', 80, NULL, NULL),
    (2238, 'feraligite', NULL, 'mega-stones', 80, NULL, NULL),
    (136, 'figy-berry', '무화열매', 'picky-healing', 10, '포켓몬에게 지니게 하면 위급할 때 HP를 회복한다. 싫어하는 맛이면 혼란에 빠진다.', 'Held: Consumed at 1/2 max HP to restore 1/8 max HP. Confuses Pokémon that dislike spicy flavor.'),
    (280, 'fist-plate', '주먹플레이트', 'plates', 90, '격투타입의 석판. 지니게 하면 격투타입 기술의 위력이 강해진다.', 'Held: Fighting-Type moves from holder do 20% more damage. Changes Arceus’s and Judgment’s type to Fighting.'),
    (250, 'flame-orb', '화염구슬', 'bad-held-items', 30, '만지면 열을 내는 이상한 구슬. 지니게 하면 배틀 중에 화상 상태가 된다.', 'Held: Inflicts Burn on the holder at the end of the turn. Activates after Burn damage would occur.'),
    (275, 'flame-plate', '불구슬플레이트', 'plates', 90, '불꽃타입의 석판. 지니게 하면 불꽃타입 기술의 위력이 강해진다.', 'Held: Fire-Type moves from holder do 20% more damage. Changes Arceus’s and Judgment’s type to Fire.'),
    (582, 'float-stone', '가벼운돌', 'held-items', 30, '매우 가벼운 돌. 지니게 하면 포켓몬의 체중이 가벼워진다.', 'Held: Holder has 0.5× weight.'),
    (2253, 'floettite', NULL, 'mega-stones', 80, NULL, NULL),
    (207, 'focus-band', '기합의머리띠', 'held-items', 10, '지니게 하면 기절할 듯한 기술을 받아도 HP를 1 남겨서 견디기도 한다.', 'Held: Holder has 10% chance to survive attacks or self-inflicted damage at 1 HP.'),
    (252, 'focus-sash', '기합의띠', 'held-items', 10, '지니게 하면 HP가 꽉 찼을 때 기절할 듯한 기술을 당해도 HP 1로 한 번은 버틴다.', 'Held: Holder survives any single-hit attack at 1 HP if at max HP, then the item is consumed.'),
    (2240, 'froslassite', NULL, 'mega-stones', 80, NULL, NULL),
    (293, 'full-incense', '만복향로', 'bad-held-items', 10, '이상한 향기의 향로. 지니게 한 포켓몬은 여느 때보다 행동이 느려진다.', 'Held: Holder moves last in its priority bracket. Breeding: Snorlax begets a Munchlax Egg.'),
    (797, 'galladite', '엘레이드나이트', 'mega-stones', 80, '엘레이드에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Gallade to Mega Evolve into Mega Gallade.'),
    (179, 'ganlon-berry', '용아열매', 'in-a-pinch', 10, '포켓몬에게 지니게 하면 위급할 때 자신의 방어가 올라간다.', 'Held: Consumed at 1/4 max HP to boost Defense.'),
    (722, 'garchompite', '한카리아스나이트', 'mega-stones', 80, '한카리아스에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Garchomp to Mega Evolve into Mega Garchomp.'),
    (2267, 'garchompite-z', NULL, 'mega-stones', 80, NULL, NULL),
    (696, 'gardevoirite', '가디안나이트', 'mega-stones', 80, '가디안에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Gardevoir to Mega Evolve into Mega Gardevoir.'),
    (695, 'gengarite', '팬텀나이트', 'mega-stones', 80, '팬텀에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Gengar to Mega Evolve into Mega Gengar.'),
    (804, 'glalitite', '얼음귀신나이트', 'mega-stones', 80, '얼음귀신에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Glalie to Mega Evolve into Mega Glalie.'),
    (2277, 'glimmoranite', NULL, 'mega-stones', 80, NULL, NULL),
    (2272, 'golisopite', NULL, 'mega-stones', 80, NULL, NULL),
    (2269, 'golurkite', NULL, 'mega-stones', 80, NULL, NULL),
    (901, 'grassy-seed', '그래스시드', 'held-items', 10, '포켓몬에게 지니게 하면 그래스필드일 때 사용하여 방어가 올라간다.', 'Held: Consumed on Grassy Terrain and raises the holder’s Defense by one stage.'),
    (2251, 'greninjite', NULL, 'mega-stones', 80, NULL, NULL),
    (263, 'grip-claw', '끈기갈고리손톱', 'held-items', 90, '지니게 하면 조이기나 김밥말이 등 데미지를 계속 주는 기술의 턴 수가 늘어난다.', 'Held: Holder’s multi-turn trapping moves last 5 turns.'),
    (442, 'griseous-orb', '백금옥', 'species-specific', 60, '기라티나에게 지니게 하면 드래곤과 고스트타입 기술의 위력이 올라가는 반짝반짝 빛나는 구슬.', 'Boosts the damage from Giratina’s Dragon-type and Ghost-type moves by 20%, and transforms it into Origin Forme.'),
    (55, 'guard-spec', '이펙트가드', 'stat-boosts', 30, '배틀 중 5턴 동안 같은 편의 능력을 떨어뜨리지 않게 하는 도구.', 'Prevents stat changes in battle for five turns in battle.  Raises happiness.'),
    (715, 'gyaradosite', '갸라도스나이트', 'mega-stones', 80, '갸라도스에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Gyarados to Mega Evolve into Mega Gyarados.'),
    (174, 'haban-berry', '하반열매', 'type-protection', 10, '포켓몬에게 지니게 하면 효과가 뛰어난 드래곤 기술을 당했을 때 위력이 약해진다.', 'Held: Consumed when struck by a super-effective Dragon-type attack to halve the damage.'),
    (215, 'hard-stone', '딱딱한돌', 'type-enhancement', 100, '절대 깨지지 않는 돌. 지니게 하면 바위타입 기술의 위력이 올라간다.', 'Held: Rock-Type moves from holder do 20% more damage.'),
    (2257, 'hawluchanite', NULL, 'mega-stones', 80, NULL, NULL),
    (2107, 'hearthflame-mask', NULL, 'held-items', NULL, NULL, NULL),
    (261, 'heat-rock', '뜨거운바위', 'held-items', 60, '지니게 한 포켓몬이 쾌청을 쓰면 여느 때보다 쾌청의 시간이 길어진다.', 'Held: Sunny Day by the holder lasts 8 rounds instead of 5.'),
    (2241, 'heatranite', NULL, 'mega-stones', 80, NULL, NULL),
    (1178, 'heavy-duty-boots', '통굽부츠', 'held-items', 80, '발밑에 설치된 함정 등의 영향을 받지 않게 된다.', NULL),
    (719, 'heracronite', '헤라크로스나이트', 'mega-stones', 80, '헤라크로스에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Heracross to Mega Evolve into Mega Heracross.'),
    (705, 'houndoominite', '헬가나이트', 'mega-stones', 80, '헬가에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Houndoom to Mega Evolve into Mega Houndoom.'),
    (140, 'iapapa-berry', '파야열매', 'picky-healing', 10, '포켓몬에게 지니게 하면 위급할 때 HP를 회복한다. 싫어하는 맛이면 혼란에 빠진다.', 'Held: Consumed at 1/2 max HP to restore 1/8 max HP. Confuses Pokémon that dislike sour flavor.'),
    (279, 'icicle-plate', '고드름플레이트', 'plates', 90, '얼음타입의 석판. 지니게 하면 얼음타입 기술의 위력이 강해진다.', 'Held: Ice-Type moves from holder do 20% more damage. Changes Arceus’s and Judgment’s type to Ice.'),
    (259, 'icy-rock', '차가운바위', 'held-items', 40, '지니게 한 포켓몬이 싸라기눈을 쓰면 여느 때보다 싸라기눈의 시간이 길어진다.', 'Held: Hail by the holder lasts 8 rounds instead of 5.'),
    (285, 'insect-plate', '비단벌레플레이트', 'plates', 90, '벌레타입의 석판. 지니게 하면 벌레타입 기술의 위력이 강해진다.', 'Held: Bug-Type moves from holder do 20% more damage. Changes Arceus’s and Judgment’s type to Bug.'),
    (255, 'iron-ball', '검은철구', 'bad-held-items', 130, '지니게 하면 스피드가 떨어진다. 비행타입이나 부유포켓몬은 땅 기술에 맞아 버린다.', 'Held: Holder’s Speed is halved. Negates all Ground-type immunities, and makes Flying-types take neutral damage from Ground-type moves. Arena Trap. Spikes, and Toxic Spikes affect the holder.'),
    (290, 'iron-plate', '강철플레이트', 'plates', 90, '강철타입의 석판. 지니게 하면 강철타입 기술의 위력이 강해진다.', 'Held: Steel-Type moves from holder do 20% more damage. Changes Arceus’s and Judgment’s type to Steel.'),
    (714, 'kangaskhanite', '캥카나이트', 'mega-stones', 80, '캥카에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Kangaskhan to Mega Evolve into Mega Kangaskhan.'),
    (173, 'kasib-berry', '수불열매', 'type-protection', 10, '포켓몬에게 지니게 하면 효과가 뛰어난 고스트 기술을 당했을 때 위력이 약해진다.', 'Held: Consumed when struck by a super-effective Ghost-type attack to halve the damage.'),
    (167, 'kebia-berry', '으름열매', 'type-protection', 10, '포켓몬에게 지니게 하면 효과가 뛰어난 독 기술을 당했을 때 위력이 약해진다.', 'Held: Consumed when struck by a super-effective Poison-type attack to halve the damage.'),
    (198, 'kings-rock', '왕의징표석', 'held-items', 30, '지니게 하면 공격해서 데미지를 줄 때 상대를 풀죽이기도 한다.', 'Held: Damaging moves gain a 10% chance to make their target flinch. Traded on a Poliwhirl: Holder evolves into Politoed. Traded on a Slowpoke: Holder evolves into Slowking.'),
    (256, 'lagging-tail', '느림보꼬리', 'bad-held-items', 10, '매우 무거운 무언가의 꼬리. 지니게 하면 여느 때보다 행동이 느려진다.', 'Held: Holder moves last in its priority bracket.'),
    (183, 'lansat-berry', '랑사열매', 'in-a-pinch', 10, '포켓몬에게 지니게 하면 위급할 때 공격이 급소를 맞히기 쉬워진다.', 'Held: Consumed at 1/4 max HP to boost critical hit ratio by two stages.'),
    (760, 'latiasite', '라티아스나이트', 'mega-stones', 80, '라티아스에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Latias to Mega Evolve into Mega Latias.'),
    (761, 'latiosite', '라티오스나이트', 'mega-stones', 80, '라티오스에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Latios to Mega Evolve into Mega Latios.'),
    (232, 'lax-incense', '무사태평향로', 'held-items', 10, '지니게 하면 향로의 이상한 향기가 상대를 혼란시켜 기술이 명중하기 어려워진다.', 'Held: Holder’s evasion is increased by 5%. Breeding: Wobbuffet begets a Wynaut Egg.'),
    (211, 'leftovers', '먹다남은음식', 'held-items', 10, '지니게 하면 포켓몬의 HP가 배틀을 하는 동안 조금씩 회복된다.', 'Held: Restores 1/16 (6.25%) holder’s max HP at the end of each turn.'),
    (1664, 'legend-plate', NULL, 'plates', NULL, NULL, NULL),
    (178, 'liechi-berry', '치리열매', 'in-a-pinch', 10, '포켓몬에게 지니게 하면 위급할 때 자신의 공격이 올라간다.', 'Held: Consumed at 1/4 max HP to boost Attack.'),
    (247, 'life-orb', '생명의구슬', 'held-items', 30, '지니게 하면 공격할 때마다 HP가 조금씩 줄지만 기술의 위력이 올라간다.', 'Held: Holder’s moves inflict 30% extra damage, but cost 10% max HP.'),
    (213, 'light-ball', '전기구슬', 'species-specific', 30, '피카츄에게 지니게 하면 공격과 특수공격의 위력이 올라가는 이상한 구슬.', 'Doubles Pikachu’s Attack and Special Attack. Breed on Pikachu or Raichu: Pichu Egg will have Volt Tackle.'),
    (246, 'light-clay', '빛의점토', 'held-items', 30, '지니게 한 포켓몬이 빛의장막이나 리플렉터를 사용했을 때 여느 때보다 긴 시간 동안 지속된다.', 'Held: Light Screen and Reflect used by the holder last 8 rounds instead of 5.'),
    (1702, 'loaded-dice', NULL, 'held-items', NULL, NULL, NULL),
    (809, 'lopunnite', '이어롭나이트', 'mega-stones', 80, '이어롭에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Lopunny to Mega Evolve into Mega Lopunny.'),
    (712, 'lucarionite', '루카리오나이트', 'mega-stones', 80, '루카리오에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Lucario to Mega Evolve into Mega Lucario.'),
    (2268, 'lucarionite-z', NULL, 'mega-stones', 80, NULL, NULL),
    (233, 'lucky-punch', '럭키펀치', 'species-specific', 40, '행운을 부르는 글러브다. 럭키에게 지니게 하면 기술이 급소에 맞기 쉬워진다.', 'Raises Chansey’s critical hit ratio by two stages.'),
    (688, 'luminous-moss', '빛이끼', 'held-items', 30, '단 한 번 쓰면 없어지는 빛이끼. 지니게 하고 물 기술을 받으면 특수방어가 올라간다.', 'Held: If the holder is hit by a damaging Water move, raises its Special Defense by one stage.'),
    (113, 'lustrous-orb', '백옥', 'species-specific', 60, '펄기아에게 지니게 하면 드래곤과 물타입 기술의 위력이 올라가는 아름답게 반짝이는 구슬.', 'Boosts the damage from Palkia’s Dragon-type and Water-type moves by 20%.'),
    (192, 'macho-brace', '교정깁스', 'effort-training', 60, '단단하고 무거운 깁스. 지니게 하면 스피드는 떨어지지만 여느 때보다 강하게 키우기 쉽다.', 'Held: Holder gains double effort values from battles, but has halved Speed in battle.'),
    (2273, 'magearnite', NULL, 'mega-stones', 80, NULL, NULL),
    (219, 'magnet', '자석', 'type-enhancement', 30, '강력한 자석. 지니게 하면 전기타입 기술의 위력이 올라간다.', 'Held: Electric-Type moves from holder do 20% more damage.'),
    (138, 'mago-berry', '마고열매', 'picky-healing', 10, '포켓몬에게 지니게 하면 위급할 때 HP를 회복한다. 싫어하는 맛이면 혼란에 빠진다.', 'Held: Consumed at 1/2 max HP to restore 1/8 max HP. Confuses Pokémon that dislike sweet flavor.'),
    (2254, 'malamarite', NULL, 'mega-stones', 80, NULL, NULL),
    (721, 'manectite', '썬더볼트나이트', 'mega-stones', 80, '썬더볼트에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Manectric to Mega Evolve into Mega Manectric.'),
    (720, 'mawilite', '입치트나이트', 'mega-stones', 80, '입치트에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Mawile to Mega Evolve into Mega Mawile.'),
    (1631, 'max-mushrooms', '다이버섯', 'stat-boosts', 30, '다이맥스의 모습을 바꿀 수 있는 힘을 가진 버섯. 배틀 중인 포켓몬의 모든 능력을 올린다.', NULL),
    (278, 'meadow-plate', '초록플레이트', 'plates', 90, '풀타입의 석판. 지니게 하면 풀타입 기술의 위력이 강해진다.', 'Held: Grass-Type moves from holder do 20% more damage. Changes Arceus’s and Judgment’s type to Grass.'),
    (704, 'medichamite', '요가램나이트', 'mega-stones', 80, '요가램에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Medicham to Mega Evolve into Mega Medicham.'),
    (2237, 'meganiumite', NULL, 'mega-stones', 80, NULL, NULL),
    (196, 'mental-herb', '멘탈허브', 'held-items', 10, '지니게 한 포켓몬은 헤롱헤롱 상태가 되었을 때 한 번만 회복한다.', 'Held: Consumed to cure infatuation. Gen V: Also removes Taunt, Encore, Torment, Disable, and Cursed Body.'),
    (2270, 'meowsticite', NULL, 'mega-stones', 80, NULL, NULL),
    (799, 'metagrossite', '메타그로스나이트', 'mega-stones', 80, '메타그로스에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Metagross to Mega Evolve into Mega Metagross.'),
    (210, 'metal-coat', '금속코트', 'type-enhancement', 30, '특수한 금속 장막. 지니게 하면 강철타입 기술의 위력이 올라간다.', 'Held: Steel-Type moves from holder do 20% more damage.'),
    (234, 'metal-powder', '금속파우더', 'species-specific', 10, '메타몽에게 지니게 하면 방어가 올라가는 이상한 가루. 매우 잘고 단단하다.', 'Raises Ditto’s Defense and Special Defense by 50%. The boost is lost after transforming.'),
    (254, 'metronome', '메트로놈', 'held-items', 30, '지니게 하면 똑같은 기술을 연속으로 사용했을 때 위력이 올라간다. 그만두면 위력이 되돌아간다.', 'Held: Consectutive uses of the same attack have a cumulative damage boost of 10%. Maximum 100% boost.'),
    (701, 'mewtwonite-x', '뮤츠나이트X', 'mega-stones', 80, '뮤츠에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Mewtwo to Mega Evolve into Mega Mewtwo X.'),
    (702, 'mewtwonite-y', '뮤츠나이트Y', 'mega-stones', 80, '뮤츠에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Mewtwo to Mega Evolve into Mega Mewtwo Y.'),
    (186, 'micle-berry', '미클열매', 'in-a-pinch', 10, '포켓몬에게 지니게 하면 위급할 때 한 번만 기술의 명중률이 올라간다.', 'Held: Consumed at 1/4 max HP to boost accuracy of next move by 20%. (Gen IV: Perfect accuracy)'),
    (284, 'mind-plate', '이상한플레이트', 'plates', 90, '에스퍼타입의 석판. 지니게 하면 에스퍼타입 기술의 위력이 강해진다.', 'Held: Psychic-Type moves from holder do 20% more damage. Changes Arceus’s and Judgment’s type to Psychic.'),
    (216, 'miracle-seed', '기적의씨', 'type-enhancement', 30, '생명이 깃든 씨앗. 지니게 하면 풀타입 기술의 위력이 올라간다.', 'Held: Grass-Type moves from holder do 20% more damage.'),
    (1699, 'mirror-herb', NULL, 'held-items', NULL, NULL, NULL),
    (900, 'misty-seed', '미스트시드', 'held-items', 10, '포켓몬에게 지니게 하면 미스트필드일 때 사용하여 특수방어가 올라간다.', 'Held: Consumed on Misty Terrain and raises the holder’s Special Defense by one stage.'),
    (243, 'muscle-band', '힘의머리띠', 'held-items', 10, '힘이 끓어오르는 머리띠. 지니게 하면 물리 기술의 위력이 조금 올라간다.', 'Held: Boosts the damage of physical moves used by the holder by 10%.'),
    (220, 'mystic-water', '신비의물방울', 'type-enhancement', 30, '물방울 모양의 보석. 지니게 하면 물타입 기술의 위력이 올라간다.', 'Held: Water-Type moves from holder do 20% more damage.'),
    (223, 'never-melt-ice', '녹지않는얼음', 'type-enhancement', 30, '열을 가까이하지 않게 하는 얼음. 지니게 하면 얼음타입 기술의 위력이 올라간다.', 'Held: Ice-Type moves from holder do 20% more damage.'),
    (161, 'occa-berry', '오카열매', 'type-protection', 10, '포켓몬에게 지니게 하면 효과가 뛰어난 불꽃 기술을 당했을 때 위력이 약해진다.', 'Held: Consumed when struck by a super-effective Fire-type attack to halve the damage.'),
    (291, 'odd-incense', '괴상한향로', 'type-enhancement', 10, '이상한 향기의 향로. 지니게 하면 에스퍼타입 기술의 위력이 올라간다.', 'Held: Psychic-Type moves from holder do 20% more damage. Breeding: Mr. Mime begets a Mime Jr. Egg.'),
    (616, 'pass-orb', '딜구슬', 'held-items', 30, '딜파워를 발생시킬 때 사용하는 하나지방의 파워가 담긴 이상한 구슬.', 'Activates Pass Powers.'),
    (162, 'passho-berry', '꼬시개열매', 'type-protection', 10, '포켓몬에게 지니게 하면 효과가 뛰어난 물 기술을 당했을 때 위력이 약해진다.', 'Held: Consumed when struck by a super-effective Water-type attack to halve the damage.'),
    (170, 'payapa-berry', '야파열매', 'type-protection', 10, '포켓몬에게 지니게 하면 효과가 뛰어난 에스퍼 기술을 당했을 때 위력이 약해진다.', 'Held: Consumed when struck by a super-effective Psychic-type attack to halve the damage.'),
    (181, 'petaya-berry', '야타비열매', 'in-a-pinch', 10, '포켓몬에게 지니게 하면 위급할 때 자신의 특수공격이 올라간다.', 'Held: Consumed at 1/4 max HP to boost Special Attack.'),
    (803, 'pidgeotite', '피죤투나이트', 'mega-stones', 80, '피죤투에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Pidgeot to Mega Evolve into Mega Pidgeot.'),
    (891, 'pink-nectar', '연분홍꿀', 'species-specific', 10, '로열 애버뉴 화단에서 손에 넣은 꽃의 꿀. 특정 포켓몬의 모습을 바꾼다.', 'Changes Oricorio to Pa’u Style.'),
    (710, 'pinsirite', '쁘사이저나이트', 'mega-stones', 80, '쁘사이저에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Pinsir to Mega Evolve into Mega Pinsir.'),
    (684, 'pixie-plate', '정령플레이트', 'plates', 90, '페어리타입의 석판. 지니게 하면 페어리타입 기술의 위력이 강해진다.', 'Held: Fairy-Type moves from holder do 20% more damage. Changes Arceus’s and Judgment’s type to Fairy.'),
    (222, 'poison-barb', '독바늘', 'type-enhancement', 70, '독이 있는 작은 침. 지니게 하면 독타입 기술의 위력이 올라간다.', 'Held: Poison-Type moves from holder do 20% more damage.'),
    (270, 'power-anklet', '파워앵클릿', 'effort-training', 70, '지니게 하면 스피드는 떨어지지만 여느 때보다 포켓몬의 스피드를 올리면서 키우기가 쉽다.', 'Held: Holder gains 4 Speed effort values, but has halved Speed in battle.'),
    (269, 'power-band', '파워밴드', 'effort-training', 70, '지니게 하면 스피드는 떨어지지만 여느 때보다 포켓몬의 특수방어를 올리면서 키우기가 쉽다.', 'Held: Holder gains 4 Special Defense effort values, but has halved Speed in battle.'),
    (267, 'power-belt', '파워벨트', 'effort-training', 70, '지니게 하면 스피드는 떨어지지만 여느 때보다 포켓몬의 방어를 올리면서 키우기가 쉽다.', 'Held: Holder gains 4 Defense effort values, but has halved Speed in battle.'),
    (266, 'power-bracer', '파워리스트', 'effort-training', 70, '지니게 하면 스피드는 떨어지지만 여느 때보다 포켓몬의 공격을 올리면서 키우기가 쉽다.', 'Held: Holder gains 4 Attack effort values, but has halved Speed in battle.'),
    (248, 'power-herb', '파워풀허브', 'held-items', 10, '지니게 한 포켓몬은 한 번만 1턴째에 힘을 모으는 기술을 바로 사용할 수가 있다.', 'Held: Both turns of a two-turn charge move happen at once. Consumed upon use.'),
    (268, 'power-lens', '파워렌즈', 'effort-training', 70, '지니게 하면 스피드는 떨어지지만 여느 때보다 포켓몬의 특수공격을 올리면서 키우기가 쉽다.', 'Held: Holder gains 4 Special Attack effort values, but has halved Speed in battle.'),
    (271, 'power-weight', '파워웨이트', 'effort-training', 70, '지니게 하면 스피드는 떨어지지만 여느 때보다 포켓몬의 HP를 올리면서 키우기가 쉽다.', 'Held: Holder gains 4 HP effort values, but has halved Speed in battle.'),
    (897, 'protective-pads', '방호패드', 'held-items', 30, '공격하는 상대와 접촉해서 받게 되는 효과를 받지 않게 한다.', 'Held: Prevents side effects of contact moves used on the holder.'),
    (899, 'psychic-seed', '사이코시드', 'held-items', 10, '포켓몬에게 지니게 하면 사이코필드일 때 사용하여 특수방어가 올라간다.', 'Held: Consumed on Psychic Terrain and raises the holder’s Special Defense by one stage.'),
    (1700, 'punching-glove', NULL, 'held-items', NULL, NULL, NULL),
    (892, 'purple-nectar', '보라꿀', 'species-specific', 10, '포니 화원에서 손에 넣은 꽃의 꿀. 특정 포켓몬의 모습을 바꾼다.', 'Changes Oricorio to Sensu Style.'),
    (2252, 'pyroarite', NULL, 'mega-stones', 80, NULL, NULL),
    (194, 'quick-claw', '선제공격손톱', 'held-items', 80, '가볍고 날카로운 손톱. 지니게 하면 상대보다 먼저 행동할 수도 있다.', 'Held: Holder has a 3/16 (18.75%) chance to move first.'),
    (251, 'quick-powder', '스피드파우더', 'species-specific', 10, '메타몽에게 지니게 하면 스피드가 올라가는 이상한 가루. 매우 잘고 단단하다.', 'Doubles Ditto’s Speed when held. The boost is lost after transforming.'),
    (2262, 'raichunite-x', NULL, 'mega-stones', 80, NULL, NULL),
    (2263, 'raichunite-y', NULL, 'mega-stones', 80, NULL, NULL),
    (303, 'razor-claw', '예리한손톱', 'held-items', 80, '날카롭고 뾰족한 손톱. 지니게 하면 기술이 급소에 맞기 쉬워진다.', 'Held: Raises the holder’s critical hit ratio by one stage. Held by a Sneasel while levelling up at night: Holder evolves into Weavile.'),
    (304, 'razor-fang', '예리한이빨', 'held-items', 30, '날카롭고 뾰족한 이빨. 지니게 하면 데미지를 줬을 때 풀죽게 하기도 한다.', 'Held: Damaging moves gain a 10% chance to make their target flinch. Held by a Gligar while levelling up: Holder evolves into Gliscor.'),
    (585, 'red-card', '레드카드', 'held-items', 10, '이상한 힘이 있는 카드. 지니게 하면 기술을 사용한 상대를 퇴장시킬 수 있다.', 'Held: When the holder takes damage from a move, the opponent switches out for another random party Pokémon. Consumed after use.'),
    (889, 'red-nectar', '다홍꿀', 'species-specific', 10, '울라울라 화원에서 손에 넣은 꽃의 꿀. 특정 포켓몬의 모습을 바꾼다.', 'Changes Oricorio to Baile Style.'),
    (164, 'rindo-berry', '린드열매', 'type-protection', 10, '포켓몬에게 지니게 하면 효과가 뛰어난 풀 기술을 당했을 때 위력이 약해진다.', 'Held: Consumed when struck by a super-effective Grass-type attack to halve the damage.'),
    (586, 'ring-target', '겨냥표적', 'held-items', 10, '포켓몬 타입의 상성 때문에 무효였던 기술이 맞게 되어 버린다.', 'Held: Negates the holder’s type immunities. Ability immunities are not removed.'),
    (292, 'rock-incense', '암석향로', 'type-enhancement', 10, '이상한 향기의 향로. 지니게 하면 바위타입 기술의 위력이 올라간다.', 'Held: Rock-Type moves from holder do 20% more damage. Breeding: Sudowoodo begets a Bonsly Egg.'),
    (583, 'rocky-helmet', '울퉁불퉁멧', 'held-items', 60, '포켓몬에게 지니게 하면 타격 기술을 당했을 때 상대에게도 데미지를 준다.', 'Held: When the holder is hit by a contact move, the attacking Pokémon takes 1/6 its max HP in damage.'),
    (1180, 'room-service', '룸서비스', 'held-items', 100, '포켓몬에게 지니게 하면 트릭룸일 때 사용하여 스피드가 떨어진다.', NULL),
    (295, 'rose-incense', '꽃향로', 'type-enhancement', 10, '이상한 향기의 향로. 지니게 하면 풀타입 기술의 위력이 올라간다.', 'Held: Grass-Type moves from holder do 20% more damage. Breeding: Roselia or Roserade beget a Budew Egg.'),
    (723, 'roseli-berry', '로셀열매', 'type-protection', 10, '포켓몬에게 지니게 하면 효과가 뛰어난 페어리 기술을 당했을 때 위력이 약해진다.', 'Held: Consumed when struck by a super-effective Fairy-type attack to halve the damage.'),
    (1162, 'rusted-shield', '녹슨방패', 'species-specific', NULL, '먼 옛날의 영웅이 재앙을 막는 데 사용했다고 전해지는 방패지만 지금은 녹이 슬고 닳아버렸다.', NULL),
    (1161, 'rusted-sword', '녹슨검', 'species-specific', NULL, '먼 옛날의 영웅이 재앙을 막는 데 사용했다고 전해지는 검이지만 지금은 녹이 슬고 닳아버렸다.', NULL),
    (795, 'sablenite', '깜까미나이트', 'mega-stones', 80, '깜까미에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Sableye to Mega Evolve into Mega Sableye.'),
    (690, 'safety-goggles', '방진고글', 'held-items', 80, '날씨로 인한 데미지뿐만 아니라 가루를 내보내는 기술의 효과도 막을 수 있는 고글.', 'Held: Prevents damage from powder moves and the damage from Hail and Sandstorm.'),
    (180, 'salac-berry', '캄라열매', 'in-a-pinch', 10, '포켓몬에게 지니게 하면 위급할 때 자신의 스피드가 올라간다.', 'Held: Consumed at 1/4 max HP to boost Speed.'),
    (810, 'salamencite', '보만다나이트', 'mega-stones', 80, '보만다에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Salamence to Mega Evolve into Mega Salamence.'),
    (794, 'sceptilite', '나무킹나이트', 'mega-stones', 80, '나무킹에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Sceptile to Mega Evolve into Mega Sceptile.'),
    (709, 'scizorite', '핫삼나이트', 'mega-stones', 80, '핫삼에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Scizor to Mega Evolve into Mega Scizor.'),
    (2245, 'scolipite', NULL, 'mega-stones', 80, NULL, NULL),
    (209, 'scope-lens', '초점렌즈', 'held-items', 30, '약점이 보이는 렌즈. 지니게 한 포켓몬의 기술이 급소에 맞기 쉬워진다.', 'Held: Raises the holder’s critical hit ratio by one stage.'),
    (2274, 'scovillainite', NULL, 'mega-stones', 80, NULL, NULL),
    (2246, 'scraftinite', NULL, 'mega-stones', 80, NULL, NULL),
    (231, 'sea-incense', '바닷물향로', 'type-enhancement', 10, '이상한 향기의 향로. 지니게 하면 물타입 기술의 위력이 올라간다.', 'Held: Water-Type moves from holder do 20% more damage. Breeding: Marill or Azumarill beget an Azurill Egg.'),
    (221, 'sharp-beak', '예리한부리', 'type-enhancement', 50, '길고 뾰족한 부리. 지니게 하면 비행타입 기술의 위력이 올라간다.', 'Held: Flying-Type moves from holder do 20% more damage.'),
    (800, 'sharpedonite', '샤크니아나이트', 'mega-stones', 80, '샤크니아에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Sharpedo to Mega Evolve into Mega Sharpedo.'),
    (272, 'shed-shell', '아름다운허물', 'held-items', 10, '튼튼하고 단단한 허물. 지니게 한 포켓몬은 교대 포켓몬과 반드시 교체할 수 있다.', 'Held: Holder can bypass all trapping effects and switch out. Multi-turn moves still cannot be switched out of.'),
    (230, 'shell-bell', '조개껍질방울', 'held-items', 30, '지니게 한 포켓몬이 공격하여 상대에게 데미지를 줬을 때 HP를 조금 회복할 수 있다.', 'Held: Holder receives 1/8 of the damage it deals when attacking.'),
    (564, 'shock-drive', '번개카세트', 'species-specific', 70, '게노세크트에게 지니게 하면 테크노버스터라는 기술이 전기타입으로 바뀌는 카세트.', 'Grants Genesect a yellow, Electric-type Techno Blast.'),
    (168, 'shuca-berry', '슈캐열매', 'type-protection', 10, '포켓몬에게 지니게 하면 효과가 뛰어난 땅 기술을 당했을 때 위력이 약해진다.', 'Held: Consumed when struck by a super-effective Ground-type attack to halve the damage.'),
    (228, 'silk-scarf', '실크스카프', 'type-enhancement', 10, '감촉이 좋은 스카프. 지니게 하면 노말타입 기술의 위력이 올라간다.', 'Held: Normal-Type moves from holder do 20% more damage.'),
    (199, 'silver-powder', '은빛가루', 'type-enhancement', 10, '은색으로 반짝이는 가루. 지니게 하면 벌레타입 기술의 위력이 올라간다.', 'Held: Bug-Type moves from holder do 20% more damage.'),
    (2239, 'skarmorite', NULL, 'mega-stones', 80, NULL, NULL),
    (283, 'sky-plate', '푸른하늘플레이트', 'plates', 90, '비행타입의 석판. 지니게 하면 비행타입 기술의 위력이 강해진다.', 'Held: Flying-Type moves from holder do 20% more damage. Changes Arceus’s and Judgment’s type to Flying.'),
    (801, 'slowbronite', '야도란나이트', 'mega-stones', 80, '야도란에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Slowbro to Mega Evolve into Mega Slowbro.'),
    (205, 'smoke-ball', '연막탄', 'held-items', 30, '지니게 한 포켓몬은 야생 포켓몬과의 배틀에서 반드시 도망칠 수 있다.', 'Held: Allows the Holder to escape from any wild battle.'),
    (260, 'smooth-rock', '보송보송바위', 'held-items', 10, '지니게 한 포켓몬이 모래바람을 쓰면 여느 때보다 모래바람의 시간이 길어진다.', 'Held: Sandstorm by the holder lasts 8 rounds instead of 5.'),
    (689, 'snowball', '눈덩이', 'held-items', 30, '단 한 번 쓰면 없어지는 눈덩이. 지니게 하고 얼음 기술을 받으면 공격이 올라간다.', 'Held: If the holder is hit by a damaging Ice move, raises its Attack by one stage.'),
    (214, 'soft-sand', '부드러운모래', 'type-enhancement', 10, '만지면 보슬보슬한 모래. 지니게 하면 땅타입 기술의 위력이 올라간다.', 'Held: Ground-Type moves from holder do 20% more damage.'),
    (202, 'soul-dew', '마음의물방울', 'species-specific', 30, '라티오스나 라티아스에게 지니게 하면 에스퍼와 드래곤타입 기술의 위력이 올라가는 이상한 구슬.', 'Raises Latias and Latios’s Special Attack and Special Defense by 50%.'),
    (224, 'spell-tag', '저주의부적', 'type-enhancement', 30, '괴상하고 으스스한 부적. 지니게 하면 고스트타입 기술의 위력이 올라간다.', 'Held: Ghost-Type moves from holder do 20% more damage.'),
    (276, 'splash-plate', '물방울플레이트', 'plates', 90, '물타입의 석판. 지니게 하면 물타입 기술의 위력이 강해진다.', 'Held: Water-Type moves from holder do 20% more damage. Changes Arceus’s and Judgment’s type to Water.'),
    (287, 'spooky-plate', '원령플레이트', 'plates', 90, '고스트타입의 석판. 지니게 하면 고스트타입 기술의 위력이 강해진다.', 'Held: Ghost-Type moves from holder do 20% more damage. Changes Arceus’s and Judgment’s type to Ghost.'),
    (2266, 'staraptite', NULL, 'mega-stones', 80, NULL, NULL),
    (184, 'starf-berry', '스타열매', 'in-a-pinch', 10, '포켓몬에게 지니게 하면 위급할 때 능력 중의 하나가 크게 올라간다.', 'Held: Consumed at 1/4 max HP to boost a random stat by two stages.'),
    (2235, 'starminite', NULL, 'mega-stones', 80, NULL, NULL),
    (802, 'steelixite', '강철톤나이트', 'mega-stones', 80, '강철톤에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Steelix to Mega Evolve into Mega Steelix.'),
    (236, 'stick', '대파', 'species-specific', 60, '매우 길고 단단한 줄기. 파오리에게 지니게 하면 기술이 급소에 맞기 쉬워진다.', 'Raises Farfetch’d’s critical hit ratio by two stages.'),
    (265, 'sticky-barb', '끈적끈적바늘', 'bad-held-items', 80, '지니게 하면 매 턴 데미지를 입는다. 자신에게 접촉해온 상대에게 들러붙기도 한다.', 'Held: Holder takes 1/8 (12.5%) its max HP at the end of each turn. When the holder is hit by a contact move, the attacking Pokémon takes 1/8 its max HP in damage and receive the item if not holding one.'),
    (286, 'stone-plate', '암석플레이트', 'plates', 90, '바위타입의 석판. 지니게 하면 바위타입 기술의 위력이 강해진다.', 'Held: Rock-Type moves from holder do 20% more damage. Changes Arceus’s and Judgment’s type to Rock.'),
    (793, 'swampertite', '대짱이나이트', 'mega-stones', 80, '대짱이에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Swampert to Mega Evolve into Mega Swampert.'),
    (171, 'tanga-berry', '리체열매', 'type-protection', 10, '포켓몬에게 지니게 하면 효과가 뛰어난 벌레 기술을 당했을 때 위력이 약해진다.', 'Held: Consumed when struck by a super-effective Bug-type attack to halve the damage.'),
    (2276, 'tatsugirinite', NULL, 'mega-stones', 80, NULL, NULL),
    (896, 'terrain-extender', '그라운드코트', 'held-items', 60, '지니게 한 포켓몬이 기술이나 특성으로 필드를 사용했을 때 여느 때보다 긴 시간 동안 지속된다.', 'Held: Extends the holder’s Terrain effects to 8 turns.'),
    (235, 'thick-club', '굵은뼈', 'species-specific', 90, '무언가의 단단한 뼈. 탕구리 혹은 텅구리에게 지니게 하면 공격이 올라간다.', 'Doubles Cubone or Marowak’s Attack.'),
    (1176, 'throat-spray', '목스프레이', 'held-items', 30, '소리 기술을 사용하면 특수공격이 올라간다.', NULL),
    (249, 'toxic-orb', '맹독구슬', 'bad-held-items', 30, '만지면 독을 발산하는 이상한 구슬. 지니게 하면 배틀 중에 맹독 상태가 된다.', 'Held: Inflicts Toxic on the holder at the end of the turn. Activates after Poison damage would occur.'),
    (281, 'toxic-plate', '맹독플레이트', 'plates', 90, '독타입의 석판. 지니게 하면 독타입 기술의 위력이 강해진다.', 'Held: Poison-Type moves from holder do 20% more damage. Changes Arceus’s and Judgment’s type to Poison.'),
    (225, 'twisted-spoon', '휘어진스푼', 'type-enhancement', 30, '염동력을 담은 숟가락. 지니게 하면 에스퍼타입 기술의 위력이 올라간다.', 'Held: Psychic-Type moves from holder do 20% more damage.'),
    (708, 'tyranitarite', '마기라스나이트', 'mega-stones', 80, '마기라스에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Tyranitar to Mega Evolve into Mega Tyranitar.'),
    (1181, 'utility-umbrella', '만능우산', 'held-items', 60, '지니게 한 포켓몬은 비와 햇살이 강할 때의 영향을 받지 않게 된다.', NULL),
    (698, 'venusaurite', '이상해꽃나이트', 'mega-stones', 80, '이상해꽃에게 지니게 하면 배틀할 때 메가진화할 수 있는 신비한 메가스톤의 일종.', 'Held: Allows Venusaur to Mega Evolve into Mega Venusaur.'),
    (2234, 'victreebelite', NULL, 'mega-stones', 80, NULL, NULL),
    (163, 'wacan-berry', '초나열매', 'type-protection', 10, '포켓몬에게 지니게 하면 효과가 뛰어난 전기 기술을 당했을 때 위력이 약해진다.', 'Held: Consumed when struck by a super-effective Electric-type attack to halve the damage.'),
    (294, 'wave-incense', '잔물결향로', 'type-enhancement', 10, '이상한 향기의 향로. 지니게 하면 물타입 기술의 위력이 올라간다.', 'Held: Water-Type moves from holder do 20% more damage. Breeding: Mantine begets a Mantyke Egg.'),
    (682, 'weakness-policy', '약점보험', 'held-items', 80, '약점을 공격당했을 때 공격과 특수공격이 각각 크게 올라간다.', 'Held: When the holder is hit by a super effective move, its Attack and Special Attack raise by two stages.'),
    (2106, 'wellspring-mask', NULL, 'held-items', NULL, NULL, NULL),
    (191, 'white-herb', '하양허브', 'held-items', 10, '지니게 한 포켓몬의 능력이 떨어졌을 때 한 번만 원래 상태로 돌아온다.', 'Held: Resets all lowered stats to normal at end of turn. Consumed after use.'),
    (242, 'wide-lens', '광각렌즈', 'held-items', 10, '물건이 크게 보이는 렌즈. 지니게 하면 기술의 명중률이 조금 올라간다.', 'Held: Provides a 1/10 (10%) boost in accuracy to the holder.'),
    (137, 'wiki-berry', '위키열매', 'picky-healing', 10, '포켓몬에게 지니게 하면 위급할 때 HP를 회복한다. 싫어하는 맛이면 혼란에 빠진다.', 'Held: Consumed at 1/2 max HP to restore 1/8 max HP. Confuses Pokémon that dislike dry flavor.'),
    (244, 'wise-glasses', '박식안경', 'held-items', 10, '두꺼운 렌즈를 붙인 안경. 지니게 하면 특수 기술의 위력이 조금 올라간다.', 'Held: Boosts the damage of special moves used by the holder by 1/10 (10%).'),
    (60, 'x-accuracy', '잘-맞히기', 'stat-boosts', 30, '배틀 중인 포켓몬의 명중률을 크게 올리는 도구. 포켓몬을 볼에 넣어버리면 원래대로 되돌아간다.', 'Raises accuracy by one stage in battle.  Raises happiness.'),
    (57, 'x-attack', '플러스파워', 'stat-boosts', 30, '배틀 중인 포켓몬의 공격을 크게 올리는 도구. 포켓몬을 볼에 넣어버리면 원래대로 되돌아간다.', 'Raises Attack by one stage in battle.  Raises happiness.'),
    (58, 'x-defense', '디펜드업', 'stat-boosts', 30, '배틀 중인 포켓몬의 방어를 크게 올리는 도구. 포켓몬을 볼에 넣어버리면 원래대로 되돌아간다.', 'Raises Defense by one stage in battle.  Raises happiness.'),
    (61, 'x-sp-atk', '스페셜업', 'stat-boosts', 30, '배틀 중인 포켓몬의 특수공격을 크게 올리는 도구. 포켓몬을 볼에 넣어버리면 원래대로 되돌아간다.', 'Raises Special Attack by one stage in battle.  Raises happiness.'),
    (62, 'x-sp-def', '스페셜가드', 'stat-boosts', 30, '배틀 중인 포켓몬의 특수방어를 크게 올리는 도구. 포켓몬을 볼에 넣어버리면 원래대로 되돌아간다.', 'Raises Special Defense by one stage in battle.  Raises happiness.'),
    (59, 'x-speed', '스피드업', 'stat-boosts', 30, '배틀 중인 포켓몬의 스피드를 크게 올리는 도구. 포켓몬을 볼에 넣어버리면 원래대로 되돌아간다.', 'Raises Speed by one stage in battle.  Raises happiness.'),
    (165, 'yache-berry', '플카열매', 'type-protection', 10, '포켓몬에게 지니게 하면 효과가 뛰어난 얼음 기술을 당했을 때 위력이 약해진다.', 'Held: Consumed when struck by a super-effective Ice-type attack to halve the damage.'),
    (890, 'yellow-nectar', '진노랑꿀', 'species-specific', 10, '멜레멜레 화원에서 손에 넣은 꽃의 꿀. 특정 포켓몬의 모습을 바꾼다.', 'Changes Oricorio to Pom-Pom Style.'),
    (277, 'zap-plate', '우레플레이트', 'plates', 90, '전기타입의 석판. 지니게 하면 전기타입 기술의 위력이 강해진다.', 'Held: Electric-Type moves from holder do 20% more damage. Changes Arceus’s and Judgment’s type to Electric.'),
    (2260, 'zeraorite', NULL, 'mega-stones', 80, NULL, NULL),
    (253, 'zoom-lens', '포커스렌즈', 'held-items', 10, '지니게 한 포켓몬이 상대보다도 행동하는 것이 늦을 때 기술이 명중하기 쉬워진다.', 'Held: Provides a 1/5 (20%) boost in accuracy if the holder moves after the target.'),
    (2258, 'zygardite', NULL, 'mega-stones', 80, NULL, NULL);
